#cloud-config
users:
  - name: ${ssh_username}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
runcmd:
  - echo "127.0.0.1 ${name}" >> /etc/hosts
# packages:
#   - tree